### ISSUE TITLE
Improve the way we allocate and use memory for GPU batch decoding

### ISSUE THREAD

**Issue by ahmadsharif1** [pytorch/torchcodec#189]
Currently when we are doing batch decoding, using get frames_at_indexes, we allocate the memory on the host, and then we all allocate each frame independently and then copy the memory into the batch memory.

Memory is allocated here for the batch:

https://github.com/pytorch/torchcodec/blob/f4065f1b477148cfb0ef94167fb0bf3a63803e55/src/torchcodec/decoders/_core/VideoDecoder.cpp#L1021

The copy is done here from frame to batch memory:

https://github.com/pytorch/torchcodec/blob/f4065f1b477148cfb0ef94167fb0bf3a63803e55/src/torchcodec/decoders/_core/VideoDecoder.cpp#L1031

This is wasteful especially when we are doing GPU recording because we incur multiple device to host transfers -- one per frame.

Action items:
1. We should respect the device when we are allocating the batch tensor memory.
2. We should directly use the batch sensor memory instead of incurring an extra memcpy.

**Comment by NicolasHug** [comment]
Adding bug label since batch-decoding on CUDA currently returns a CPU tensor (ref: https://github.com/pytorch/torchcodec/issues/268)

**Comment by NicolasHug** [comment]
This was incorrectly closed by https://github.com/pytorch/torchcodec/pull/266, I think this is still outstanding

**Comment by ahmadsharif1** [comment]
Is this still an issue? I thought I fixed this already in https://github.com/pytorch/torchcodec/pull/319
